### PR TITLE
Separating HTML and styles, converting CSS to SCSS, adding more tooling

### PR DESCRIPTION
**Pull request by salaros**
* now HTML source file resides in a separate folder (./src)
* SCSS is compiled to CSS and injected into email.html file
* then CSS is in-lined in email-inlined.html file

### CODE REVIEW

**Comment by leemunroe** [comment]
@salaros This is cool although I'm deliberately trying to keep this repo simple and point people to other repos like https://github.com/leemunroe/grunt-email-workflow/ if they want a build workflow. 

Happy to link to your Gulp solution from the readme. What do you think?

**Comment by salaros** [comment]
@leemunroe Sorry I didn't realized that. You'd consider adding a [contributing.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) file or a section in the readme file containing this info.
I've intentionally kept my implementation as close as possible (in terms of results, paths etc) to your repo, hoping I could help you and project contributors :)
Anyway having a link to my repo in the readme would be really great!
Thanks again for such a cool and useful project!

**Comment by salaros** [comment]
@leemunroe I think you can close it. I didn't do it myself, because I thought this PR is a reminder for adding the link into readme file

**Comment by leemunroe** [comment]
@salaros Yes no problem. Keeping this here as a reminder to myself to add the link and some contributing notes. I agree I should make this clearer.

Do you want me to link to the [fork](https://github.com/salaros/responsive-html-email-template)? If so you probably want to update your readme with instructions.

**Comment by salaros** [comment]
OK, I've updated readme file in my fork, as well as updated gh-pages branch.
You can add the link if you want and close this PR. Thanks again for your time

**Pull request closed without merging**
