### PR TITLE
border-radius changed

### PR DESCRIPTION
**Pull request by shuke8**
some styles are changed

### CODE REVIEW

**Comment by shuke8** [comment]
it's better than old one

**Comment by webketje** [comment]
It would be useful if you could share a screenshot (before - after). Did you actually test it in an e-mail client? How did you inline the e-mail - because there are too many differences in formatting, you probably didn't use the right one

**Review by shuke8 — COMMENTED** [review]
added some styles

**Comment by feuiuxbe** [comment]
image
excuse me, what?

**Pull request closed without merging**
