### PR TITLE
Added npm package, gulpfile and sass source

### PR DESCRIPTION
**Pull request by Wtower**

### CODE REVIEW

**Comment by leemunroe** [comment]
Thanks this looks awesome. Will take a deeper look asap.

**Comment by leemunroe** [comment]
@Wtower Have a few questions. Bear with me as I'm more familiar with Grunt than Gulp.

* I ran the `gulp` command, which built the `/build/` folder and `email.html` and `css/email.css`. What use is the `css/email.css` at this point? I would expect maybe a non-inlined version of `email.html` to make use of the CSS file. Otherwise I'm not sure what it is for.
* I previewed the [output](https://litmus.com/checklist/emails/public/c740c87) in Litmus. Compared to the [original](https://litmus.com/checklist/emails/public/f94e6de) (which was inlined with Putsmail) there are some things off like spacing and responsiveness (see below).
* Looks like the media queries and CSS in the head aren't carried across to the build. So we lose some of the responsive features.
* I wasn't sure what `In order to build the final html file you need to use gulp-inline-css` meant in the readme. Why not include this in the gulpfile?

**Comment by Wtower** [comment]
@leemunroe thank you for your review, these are excellent points. I will look into them and get back to you.

**Comment by Wtower** [comment]
Hello @leemunroe , I just look into your last comment:

> Bear with me as I'm more familiar with Grunt than Gulp.

I would be more than happy to help as much as I can. Gulp is not much different than grunt so I think you will catch up quickly. So if there is anything to tell you about it let me know, possibly it will help other users that might visit this too.

> I ran the `gulp` command, which built the `/build/` folder and `email.html` and `css/email.css`. What use is the `css/email.css` at this point? I would expect maybe a non-inlined version of `email.html` to make use of the CSS file. Otherwise I'm not sure what it is for.

Actually the `build/css/email.css` is an intermediate file that is built from the `src/email.sass` file for those familiar with it.

The proposed changes are mostly intended to be introduced in a larger project workflow. It is unlikely that my gulpfile will be used as is but mostly to take a rough idea how to build. The html file also is unlikely that will be used as is without replacing. But the sass file is more likely to be used as is directly in any replaced html without having to repeat its rules all over, but probably to simply override it.

Of course the proposed gulpfile is intended though to be able to build the html properly.

> I wasn't sure what `In order to build the final html file you need to use gulp-inline-css` meant in the readme. Why not include this in the gulpfile?

You are right. In the previous commit I used a [project of mine][1] which defines a number of common gulp tasks together with their dependencies. But that is again intended for final projects and an overkill for this one, so in my last commit I replaced it and defined the proper dependencies and gulp tasks explicitly.

> Looks like the media queries and CSS in the head aren't carried across to the build. So we lose some of the responsive features.

You are absolutely right. The `gulp-inline-css` has a couple of options: [preserveMediaQueries][2] and [applyWidhtAttributes][3] that are disabled by default and needed to be enabled explicitly. Fixed in the last commit.

> I previewed the output in Litmus. Compared to the original (which was inlined with Putsmail) there are some things off like spacing and responsiveness...

It seems this is a paid service? Could you please recheck after the last commit?

I hope the above clarifies and improves things a bit. Please do not hesitate to fire up more comments if necessary.

[1]: https://github.com/Wtower/gulpfile-ninecms
[2]: https://github.com/jonkemp/gulp-inline-css#optionspreservemediaqueries
[3]: https://github.com/jonkemp/gulp-inline-css#optionsapplywidthattributes

**Comment by leemunroe** [comment]
@Wtower Sorry for the hold up. I really like what you've done here but I fear this overcomplicates the current goals of this project. I think a lot of people appreciate the simplicity of the current repo, and for more advanced workflows they can use something like https://github.com/leemunroe/grunt-email-workflow

**Pull request closed without merging**
