### PR TITLE
Adjusting scale

### PR DESCRIPTION
**Pull request by DEBSUBHRO**

### CODE REVIEW

**Comment by leemunroe** [comment]
@DEBSUBHRO What does this do exactly? Looks fine, just would love a before/after shot to understand.

**Comment by DEBSUBHRO** [comment]
> @DEBSUBHRO What does this do exactly? Looks fine, just would love a before/after shot to understand.

I did not do anything.
Just completed the meta tag, as I had learnt earlier. I think initiating the "initial_scale" at 1.0 makes it bug-free for some unpopular browsers.

**Comment by leemunroe** [comment]
@DEBSUBHRO Is there a specific browser you can share knowledge of here or screenshot of something gone wrong? I'm hesitant to approve unless seeing the issue. It has been a while since I looked into it but my understanding is forcing initial-scale shouldn't be necessary and may disable user zooming (which is bad).

**Comment by leemunroe** [comment]
Closing as stale

**Pull request closed without merging**
