### PR TITLE
Fixed broken display of mail in Google Mail web client

### PR DESCRIPTION
**Pull request by mgraupner**
Becaue of #37 I created a working solution for Google Mail web client. This was not thoroughly tested with all E-Mail providers out there so please do your own testing!

Environment: Google Mail web client with Firefox 45 and Google Chrome Version 50.0.2661.18 dev (64-bit) both on OSX 10.11.3.

### CODE REVIEW

**Comment by leemunroe** [comment]
Is the issue that `background-color` and `align="center"` are needed? Or was the inliner tool that was used the issue?

Sorry, the inline CSS makes it awkward to diff.

**Comment by MrNicodemuz** [comment]
+1

I was expecting this to work with all major email clients. Didn't really display well in gmail. You should mention that in the README file.

**Comment by FDIM** [comment]
Works fine for me on gmail using this: https://github.com/FDIM/node-html-email-example  (same template + juice)
Only problem was padding/margin for the button. Setting padding on td worked though

**Comment by leemunroe** [comment]
Made several improvements and release 1.0.0
https://github.com/leemunroe/responsive-html-email-template/releases/tag/v1.0.0

Please let me know if these improvements addressed the issues you were having. Thanks.

**Pull request closed without merging**
